# Generated by Django 4.1 on 2024-10-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
