# Generated by Django 4.1 on 2024-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_url', models.URLField(help_text='URL изображения обложки книги')),
            ],
        ),
    ]
