# Generated by Django 4.1 on 2024-10-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, help_text='Текст книги', null=True),
        ),
    ]
